@echo off
REM WorldWind MCP Server launcher (HTTP transport)
REM seaglassfoundry.com
REM
REM Launches the WorldWind MCP server on http://localhost:8384/mcp
REM Classpath is read from target/cp.txt (generated by mvn dependency:build-classpath).
REM
REM Usage:
REM   mcp-server.bat              Start on default port 8384
REM   mcp-server.bat --port 9090  Start on custom port

setlocal enabledelayedexpansion

set PROJECT_DIR=%~dp0
set CLASSES=%PROJECT_DIR%target\classes
set CP_FILE=%PROJECT_DIR%target\cp.txt

if not exist "%CLASSES%" (
    echo ERROR: target\classes not found. Run "mvn compile" first. 1>&2
    exit /b 1
)

if not exist "%CP_FILE%" (
    echo Generating classpath... 1>&2
    call mvn -f "%PROJECT_DIR%pom.xml" dependency:build-classpath -q -DincludeScope=runtime "-Dmdep.outputFile=%CP_FILE%"
)

for /f "usebackq delims=" %%A in ("%CP_FILE%") do set "DEPS=%%A"

java -cp "%CLASSES%;!DEPS!" gov.nasa.worldwindx.mcp.WorldWindMcpServer %*
